openapi: 3.0.0
info:
  title: Integration API
  description: Recustomer API for Return and Cancel v2
  version: 1.0.0

paths:
  /orders:
    get:
      tags:
        - "Order"
      summary: get orders
      description: 注文情報を複数件取得します
      parameters:
        - $ref: "#/components/parameters/OrderIds"
      responses:
        "200":
          description: successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Orders"
    post:
      tags:
        - "Order"
      summary: post order
      description: 注文情報を作成します
      requestBody:
        $ref: "#/components/requestBodies/Order"
      responses:
        "201":
          description: successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

  /orders/{order_id}:
    get:
      tags:
        - "Order"
      summary: get one order
      description: 指定IDの注文情報を1件取得します
      parameters:
        - $ref: "#/components/parameters/OrderId"
      responses:
        "200":
          description: successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Order not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /products:
    get:
      tags:
        - "Product"
      summary: get products
      description: 商品情報を複数件取得します
      parameters:
        - $ref: "#/components/parameters/ProductIds"
      responses:
        "200":
          description: successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"

  /products/{product_id}:
    get:
      tags:
        - "Product"
      summary: get one product
      description: 商品情報を1件取得します
      parameters:
        - $ref: "#/components/parameters/ProductId"
      responses:
        "200":
          description: successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

components:
  parameters:
    OrderIds:
      name: ids
      in: query
      description: 注文idを指定する。複数指定する際にはカンマ区切りで送信する
      schema:
        type: integer
        format: int64
      example: 1,2,3
    OrderId:
      name: order_id
      in: path
      description: 指定の注文ID
      required: true
      schema:
        type: integer
        format: int64
    ProductIds:
      name: ids
      in: query
      description: 商品idを指定する。複数指定する際にはカンマ区切りで送信する
      schema:
        type: integer
        format: int64
    ProductId:
      name: product_id
      in: path
      description: 指定の商品ID
      required: true
      schema:
        type: string
  requestBodies:
    Order:
      content:
        application/json:
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
  schemas:
    Orders:
      type: array
      items:
        $ref: "#/components/schemas/Order"
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
